name: Terraform Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'eu-north-1' }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Validate
      run: terraform validate
      - name: Terraform Validate
        run: terraform validate
